baseURL = 'https://mp2i-mpi-champo.github.io/'
locale = 'fr-fr'
title = 'Ressources MP2I/MPI Champollion'
theme = 'hugo-book'

[params]
  BookToC = true
  BookSearch = true
  BookLandingPage = true
  BookLogo = 'logo.webp'
  BookFavicon = 'favicon.ico'

[markup.goldmark.parser.attribute]
  title = true
